<article>
	This application parses through song lyrics to find words and phrases that could potentially
	be an FCC profanity violation.
	<br>
	<br>
	Lyrics are pulled from <a href="http://lyrics.wikia.com/">Lyric Wikia</a>
	<br>
	<br>
	Made at/for <a href="http://hackisu.org/">Hack ISU Fall 2016</a>
	<br>
	<br>
	Email me at <a href="mailto:znewton13@gmail.com">znewton13@gmail.com</a> with questions, comments, concerns, and suggestions!
	<br>
	<br>
	Check out the Git Repository on <a href="https://github.com/znewton/lyricprof">Github</a>
	<br>
	<br>
	View my <a href="http://znewton.github.io/portfolio">Portfolio</a>
	<br>
</article>