#!/bin/bash

if [ -d "build" ]; then
  rm -rf build
fi
mkdir build
cp -r about.html index.html index.php css js lib views searchSong.php .htaccess build/

USERNAME="figgynewts"
SERVER="ftp.znewton.xyz"
DOMAIN="lyricprof.znewton.xyz"

scp -r build/* "${USERNAME}@${SERVER}:${DOMAIN}/"
